Added calls for singletons
ginetta/cockpit-sdk pull request #8
Opened 2018-10-09 16:21 UTC by nickhartjes

I extended the SDK to support singletons

2018-10-11 11:23 UTC, brunnolou requested changes
Thanks for your PR! 💪

2018-10-11 11:23 UTC, brunnolou commented on .editorconfig
> +indent_size = 2
Could you please not update this file? Since it's just removing the extra line.

2018-10-11 11:23 UTC, brunnolou commented on .eslintignore
> +examples
Same as above.

2018-10-11 17:17 UTC, nickhartjes commented
Hi @brunnolou , i removed the changes on the .editorconfig .eslintignore

2018-10-25 12:20 UTC, nickhartjes commented
Changes where done

2018-11-23 14:38 UTC, brunnolou approved these changes
Thanks! 👍

2018-11-23 14:38 UTC, merged